### ISSUE TITLE
Bug in the latest release v1.3.1

### ISSUE THREAD

**Issue by ocefpaf** [USGS-CIDA/pyGDP#100]
The latest release v1.3.1 has a bug that was fixed in master:

https://github.com/USGS-CIDA/pyGDP/blob/master/pygdp/_feature_gen.py#L1

```python
    def _generateFeatureRequest(self, typename, attribute=None, WFS_URL):
SyntaxError: non-default argument follows default argument
```

Could you issue a new release?

**Comment by dblodgett-usgs** [comment]
Release has been cut, sorry for the delay.

**Comment by ocefpaf** [comment]
@dblodgett-usgs Thanks a lot!

Here is a conda recipe for the latest release in case you are interested: https://github.com/ioos/conda-recipes/pull/180

**Comment by dblodgett-usgs** [comment]
I'm not familiar with conda recipes. Would you mind adding a quick how to use this to the pyGDP readme? I'd really appreciate it.

**Comment by ocefpaf** [comment]
Sure.  I will prepare a PR ASASP.
