### ISSUE TITLE
move jenkins builds to Travis CI?

### ISSUE THREAD

**Issue by jread-usgs** [USGS-CIDA/pyGDP#105]
travis _seems_ better suited for python builds, including the baked in ability to build on multiple version of python easily. It is also free for open source projects.

**Comment by dblodgett-usgs** [comment]
Not a bad idea... I don't know how to set it up though, want to take a crack at it?

**Comment by jread-usgs** [comment]
Sure, will do. I think you'll like it.

**Comment by ayan-usgs** [comment]
After seeing this thread, I decided to add start using travis with pysgrid (https://github.com/sgrid/pysgrid). It didn't take very long to figure out, but c-dependencies are bit tricky to deal with.

**Comment by jread-usgs** [comment]
cool @ayan-usgs any interest in getting pyGDP set up? I can help, but will be traveling starting later today.

**Comment by ayan-usgs** [comment]
@jread-usgs,

Sure, I can take a poke at it.

**Comment by jread-usgs** [comment]
@ayan-usgs any luck on this?

**Comment by ayan-usgs** [comment]
I actually haven't made an attempt yet....

**Comment by dblodgett-usgs** [comment]
This will be fixed in #141 -- we still have jenkins builds, but this is basically taken care of.
