### ISSUE TITLE
Problem with uploadShapeFile 

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CIDA/pyGDP#116]
I tried running my old dustbowl demo and it died in cell [8]:
http://nbviewer.ipython.org/gist/rsignell-usgs/cf5d61c6c6154055df5c

Is it because this line:
https://github.com/USGS-CIDA/pyGDP/blob/master/pyGDP.py#L113
says `uploadShapefile` instead of `uploadShapeFile`?

**Comment by jread-usgs** [comment]
@dblodgett-usgs there probably isn't a test for the uploader is there?

**Comment by dblodgett-usgs** [comment]
I'm not sure, that is a tough one to test. I wouldn't doubt that may have happened back when the package was refactored.

**Comment by jread-usgs** [comment]
Thanks for pointing this out @rsignell-usgs
