### ISSUE TITLE
PEP 8 Style

### ISSUE THREAD

**Issue by dblodgett-usgs** [USGS-CIDA/pyGDP#146]
Should work on improving the style conformance of pyGDP. There's been talk of doing it.

**Comment by dblodgett-usgs** [comment]
@pnorton-usgs -- can we call this issue done in spirit? Granted there may be more here, but that is for future work, right?

**Comment by pnorton-usgs** [comment]
@dblodgett-usgs -- I think we can close this. Many of the remaining PEP8 changes would alter the API so they're better left for a future major version release.
