### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CIDA/pyGDP#154]
Big merge 5 days ago -- is it time for a new release?

**Comment by rsignell-usgs** [comment]
The reason I ask is that I'd like to update the package on conda-forge to the latest version, but it's much nicer when there is a version number: 
https://anaconda.org/conda-forge/pygdp/files

**Comment by dblodgett-usgs** [comment]
Yeah. Probably. I haven't gotten a chance to test this new stuff rigorously yet though. Have you?

**Comment by rsignell-usgs** [comment]
Good point.  I should probably test my notebook with new release and make sure it runs!  :stuck_out_tongue_closed_eyes:

**Comment by rsignell-usgs** [comment]
Okay, I've confirmed the latest release works fine with my Dust Bowl notebook:
https://github.com/rsignell-usgs/binder-books/blob/master/CDI/Dust_Bowl_pyGDP.ipynb
Can we have a new release please?

**Comment by dblodgett-usgs** [comment]
I'll get after that tonight or tomorrow morning.

**Comment by dblodgett-usgs** [comment]
https://github.com/USGS-CIDA/pyGDP/releases/tag/v2.1.2
