### ISSUE TITLE
add .gitattributes

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CIDA/pyGDP#33]
![4-11-2013 6-30-08 AM](https://f.cloud.github.com/assets/1872600/366860/02115230-a293-11e2-8cdd-0943e16afa38.png)

**Comment by dblodgett-usgs** [comment]
@rsignell-usgs @jiwalker-usgs, since there is a .gitatributes, I'm closing this. If there's another issue to be fixed, please open a more detailed issue report.
